name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc-arm-none-eabi
      - name: Clone zilluss repo
        run: git clone https://github.com/zilluss/Open-Nuki-Fob.git repo
      - name: Copy your main.c
        run: cp main.c repo/
      - name: Build
        run: cd repo && make
      - name: Upload HEX
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: repo/build/*.hex
